### ISSUE TITLE
Compiling Project gives Freemarker Error

### ISSUE THREAD

**Issue by steele232** [vlingo/xoom-designer#113]
I'm trying out Xoom Developer and I hit a snag. I installed Xoom Dev via Docker and that was great. I went through a couple scenarios quickly and I had one failure-to-generate without an error and then I succeeded in generating a project with a super simple domain and CQRS turned off and things. I was able to load up that project in Intellij but mvn clean package failed with a freemarker error. It seems like the bug is deep inside vlingo so I couldn't see any code for me to be able to change. I tried this once with the UI generation toggled on and once with the UI generation toggled off and both gave freemarker errors that caused the builds to fail. mvn compile works fine but mvn package does not. Any help would be appreciated.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project hello-eric: Compilation failure
[ERROR] freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[ERROR]   ==> imports  [in template "codegen/java/RestResource.ftl" at line 21, column 8]
...
[ERROR]   FTL stack trace ("~" means nesting-related):
[ERROR]       - Failed at: #list imports as import  [in template "codegen/java/RestResource.ftl" at line 21, column 1]
```

Here is my designer-model.json (originally downloaded as com.cfm.event.json because the package name was com.cfm.event)
[designer-json.txt](https://github.com/vlingo/xoom-designer/files/6983935/designer-json.txt)

**Comment by danilo-ambrosio** [comment]
Hi @steele232 

Thanks for sharing the details. We've fixed the problem. Could you please rerun XOOM Designer via Docker by executing the following commands?

```
 $ curl -L -O https://raw.githubusercontent.com/vlingo/xoom-designer/master/docker-compose.yml
 $ docker-compose pull
 $ docker-compose up -d
```
Then, you can import the "hello-eric" model and generate your project. I also recommend that you set different names for VOs and Events. For instance, `Operation` event could be named `OperationCreated`:

![image](https://user-images.githubusercontent.com/28495827/129597645-b7fad713-b971-4ffd-9dd1-abcc28f13b7e.png)

I'm available for any clarification.

Thanks!

**Comment by steele232** [comment]
Okay, I will try that soon, thanks!

**Comment by steele232** [comment]
Hi @danilo-ambrosio , I tried a few things and got a couple different results. 

## New Model

I took your suggestion to make sure my events and things didn't use the same names and everything seemed to run smoothly after that; **I'm very happy about that!**

## New Install and Old Model

With the updated installation, I tried the old model (with some names being duplicated) and the code generated was still a little funny (didn't compile) but I had a much better error this time.

```
incompatible types: com.cfm.event.model.Operation cannot be converted to com.cfm.event.model.ssk.Operation
```

![2021_08_16_vlingo_generated_name_conflict_02](https://user-images.githubusercontent.com/18239595/129645734-6ae54e63-7a3d-44d0-b567-6ef97f2bc4d2.PNG)


And you can see how a possible confusion might come from naming things the same name. I don't know how much further you want to trace this or if you just want to train users to not name things the same thing all over the place.

**Comment by danilo-ambrosio** [comment]
Thanks for sharing your insights and lessons learned, @steele232 . We really appreciate that.

We'll implement an educational tooltip on XOOM Designer UI for making users aware that is recommended that VO and Event names have different values. Mainly for the fact that the pattern for naming Domain Events is a noun + a past tense verb (e.g. `ProductDelivered`) meaning that something relevant in the domain model happened from the business perspective.  

Contributions like yours make XOOM Designer move forward! Grateful!

**Comment by steele232** [comment]
Great! I'm glad!
