### ISSUE TITLE
xoom-designer documentation references starter.zip instead of designer.zip

### ISSUE THREAD

**Issue by bertilmuth** [vlingo/xoom-designer#124]
On this documentation website:
https://docs.vlingo.io/xoom-designer

there's the following statement:
```
Download the XOOM Designer compressed distribution file using curl.
File type: zip
curl -L -O https://github.com/vlingo/vlingo-xoom-starter/releases/latest/download/starter.zip
```

This link is broken. `starter.zip` should be replaced with `designer.zip`

**Comment by VaughnVernon** [comment]
Thanks, @bertilmuth! There were actually a few issues around that area but should now be fixed.
