### ISSUE TITLE
Bugs + Improvement ideas in Dialog

### ISSUE THREAD

**Issue by Florian-Schoenherr** [vlingo/xoom-designer#20]
1.
If I edit one of my defined Aggregates and don't change their name, I can't `Update`.
If I rename them and give them back the name they had before, the validation is also triggering.

2.
Methods should have the possiblity to either choose `Query` instead of or leave out `Event`.
I think this is pretty much a priority because of simple GET `/{id}` requests. Maybe this is already possible, but not expected by the UI.

3.
The default `get("/plurals")` REST endpoint should be on the UI
(3.2.) and the last time I generated, it handled `this::plurals` which calls `Aggregate.plurals()`, which is undefined (in an earlier version it was defined, right?)

4.
![image](https://user-images.githubusercontent.com/65456722/106672507-71a1a300-65b0-11eb-8c34-46b32a9cd060.png)
If we already do something like this, which is far less closed off than HTTP verbs, we could do this for other CRUD operations, too.

Now enough nagging, I like the new schemata interop features!
Nice work @danilo-ambrosio 😄

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Are you sure? Did you `git pull`? This very problem was fixed by the Command Router changes the other day.

**Comment by danilo-ambrosio** [comment]
@Florian-Schoenherr 
Thank you for pointing out these items. 

Item #1 has been solved in this [PR](https://github.com/vlingo/vlingo-xoom-starter/pull/21). Likely, the 2, 3 e 4 may be implemented during the VO generation feature.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr @danilo-ambrosio Can this be closed?
