### ISSUE TITLE
Updating from localStorage in Aggregate Dialog

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/xoom-designer#42]
@abdullahcalisir12 I think this one is related to #20 and #21 that was evidential not actually fixed, or at least it is still a problem if *reentering the GUI with the previous project description already in `localStorage`.

* What is meant by reentering the GUI is a complete shut down of the server browser tab, and then restarting the server and reaching a new browser tab. It would seem that there is necessary operation state regarding aggregates and/or value objects that is not being persisted and/or restored under the "reentering the GUI" situation.

1. Returning to the dialog and updating some aggregate field names and/or types, does not mark the dialog as changed so the Update button is perpetually disabled.
2. Returning to the dialog when Value Objects are in use in the aggregate type, there is no way to edit existing Value Objects. The Value Object types seem to not exist in localStorage as separate definitions, or are not being considered as existing. However, the aggregate definition still has fields that have a Value Object type, but the Value Object type seems to have no meaning other than the name.

**Comment by Florian-Schoenherr** [comment]
I think this is not a localstorage problem, but could be wrong.

**Comment by VaughnVernon** [comment]
I am not saying that it is "a `localStorage` problem." I am identifying that these problems occur when everything has been stopped and then restarted, and all that exists is whatever is in `localStorage`. The problem is obviously with Starter. As I said, there must be some operational state that exists when the project is first defined that is (1) not persisted into `localStorage`, and/or (2) not read from `localStorage` into the operational state of the newly started browser app that was previously there when the project was first defined.

**Comment by VaughnVernon** [comment]
@abdullahcalisir12 Can this be closed? I think so but not sure if all points were covered.

**Comment by abdullahcalisir12** [comment]
@VaughnVernon reentering the GUI problem is fixed way before,
a few days ago, the first point is solved by using error-warning icons.
We can update Value Objects as well so I guess all points are covered.

But to be sure you can try UI and let me know if something is missing.

**Comment by VaughnVernon** [comment]
@abdullahcalisir12 Yes, please change the Value Object dialog to also use error/warning icons, then I can review and close this.

**Comment by abdullahcalisir12** [comment]
@VaughnVernon Value Object dialog already has an error icon

**Comment by VaughnVernon** [comment]
Ah, true! Thanks for the reminder.
