### ISSUE TITLE
XOOM Designer Project Version Didn't Transition

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/xoom-designer#65]
On the latest git pull the pom.xml for xoom-designer was still at:

```
<version>1.7.1-SNAPSHOT</version>
```

Rather than:

```
<version>1.7.6-SNAPSHOT</version>
```

I don't know what happened, but it appears from history that the file was never updated to the correct `1.7.6-SNAPSHOT` version and then accidentally overwritten with `1.7.1-SNAPSHOT`.

**Comment by jakzal** [comment]
Currently we only transition packages that are tagged and deployed to sonatype. Designer isn't, nor are examples, helloworld streams-tck.

I'll have a think how to improve on this.

**Comment by jakzal** [comment]
Fixed in https://github.com/vlingo/xoom-designer/commit/765cc1839942703caa85c36d0638b4b107fe6d03#diff-f818e666850711993857dd64cadbf18d0865fd0fb60678fe836bb4cf1a4eb3ca
