### ISSUE TITLE
Working with lists within xoom designer gui

### ISSUE THREAD

**Issue by kimrow** [vlingo/xoom-designer#73]
Hello,

I've tried 1.7.7 - to try the list/set feature and within the designer, I was unable to find a dialog, which would enable me to specify List/Set type on aggregate nor value object level. Is there something I should do to see that?

Thank you,
Petr

**Comment by VaughnVernon** [comment]
Hi @kimrow It should be a drop-down at the end of the row with the field name and type. If you don't see that you might need to clear cache for localhost:port. I didn't experience issues myself. /cc @danilo-ambrosio

**Comment by danilo-ambrosio** [comment]
Hi @kimrow 
To specify List/Set type, you can fill in the highlighted fields in the images below. 
![image](https://user-images.githubusercontent.com/28495827/118159240-28ed5780-b3f3-11eb-9a64-3ac93d9145c7.png)
![image](https://user-images.githubusercontent.com/28495827/118159630-9f8a5500-b3f3-11eb-9d7c-9f1082a75b3c.png)

Can you see the Collection field in the aggregate / value object dialog?

**Comment by kimrow** [comment]
Yeah - I only executed ```mvn package``` instead of ```mvn clean install -P deployment,frontend``` - my bad. I can see it now correctly.
