### ISSUE TITLE
missing static import assertNotNull

### ISSUE THREAD

**Issue by teyckmans** [vlingo/xoom-designer#74]
Just ran into a small code generation issue for the test sources.

When using the datetime type for a state field the tests generate an assertNotNull check on the datetime field. But no static import is added for it causing a compile error.

**Comment by VaughnVernon** [comment]
Thanks @teyckmans for reporting. If you are OK with importing that class yourself it's a simple workaround until we iron out the problems.

@danilo-ambrosio Let's get this fix in for v1.7.8 along with the refactoring you are doing now. Is Wednesday or Thursday possible?

**Comment by teyckmans** [comment]
Sure no big deal, just reporting for smoothing the experience :+1:

**Comment by danilo-ambrosio** [comment]
@teyckmans 
We're grateful for helping us to improve XOOM Designer.  
I pushed the fix a few hours ago. Please, let me know if everything's working fine now.

**Comment by teyckmans** [comment]
@danilo-ambrosio just tested latest version, fix works.

Thanks for the fast response.
